// Code generated by protoc-gen-go. DO NOT EDIT.
// source: model/workflowtask.proto

package model // import "github.com/mactaggart/conductor/client/gogrpc/conductor/model"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _struct "github.com/golang/protobuf/ptypes/struct"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type WorkflowTask struct {
	Name                           string                                    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TaskReferenceName              string                                    `protobuf:"bytes,2,opt,name=task_reference_name,json=taskReferenceName,proto3" json:"task_reference_name,omitempty"`
	Description                    string                                    `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	InputParameters                map[string]*_struct.Value                 `protobuf:"bytes,4,rep,name=input_parameters,json=inputParameters,proto3" json:"input_parameters,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Type                           string                                    `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	DynamicTaskNameParam           string                                    `protobuf:"bytes,6,opt,name=dynamic_task_name_param,json=dynamicTaskNameParam,proto3" json:"dynamic_task_name_param,omitempty"`
	CaseValueParam                 string                                    `protobuf:"bytes,7,opt,name=case_value_param,json=caseValueParam,proto3" json:"case_value_param,omitempty"`
	CaseExpression                 string                                    `protobuf:"bytes,8,opt,name=case_expression,json=caseExpression,proto3" json:"case_expression,omitempty"`
	ScriptExpression               string                                    `protobuf:"bytes,22,opt,name=script_expression,json=scriptExpression,proto3" json:"script_expression,omitempty"`
	DecisionCases                  map[string]*WorkflowTask_WorkflowTaskList `protobuf:"bytes,9,rep,name=decision_cases,json=decisionCases,proto3" json:"decision_cases,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	DynamicForkTasksParam          string                                    `protobuf:"bytes,10,opt,name=dynamic_fork_tasks_param,json=dynamicForkTasksParam,proto3" json:"dynamic_fork_tasks_param,omitempty"`
	DynamicForkTasksInputParamName string                                    `protobuf:"bytes,11,opt,name=dynamic_fork_tasks_input_param_name,json=dynamicForkTasksInputParamName,proto3" json:"dynamic_fork_tasks_input_param_name,omitempty"`
	DefaultCase                    []*WorkflowTask                           `protobuf:"bytes,12,rep,name=default_case,json=defaultCase,proto3" json:"default_case,omitempty"`
	ForkTasks                      []*WorkflowTask_WorkflowTaskList          `protobuf:"bytes,13,rep,name=fork_tasks,json=forkTasks,proto3" json:"fork_tasks,omitempty"`
	StartDelay                     int32                                     `protobuf:"varint,14,opt,name=start_delay,json=startDelay,proto3" json:"start_delay,omitempty"`
	SubWorkflowParam               *SubWorkflowParams                        `protobuf:"bytes,15,opt,name=sub_workflow_param,json=subWorkflowParam,proto3" json:"sub_workflow_param,omitempty"`
	JoinOn                         []string                                  `protobuf:"bytes,16,rep,name=join_on,json=joinOn,proto3" json:"join_on,omitempty"`
	Sink                           string                                    `protobuf:"bytes,17,opt,name=sink,proto3" json:"sink,omitempty"`
	Optional                       bool                                      `protobuf:"varint,18,opt,name=optional,proto3" json:"optional,omitempty"`
	TaskDefinition                 *TaskDef                                  `protobuf:"bytes,19,opt,name=task_definition,json=taskDefinition,proto3" json:"task_definition,omitempty"`
	RateLimited                    bool                                      `protobuf:"varint,20,opt,name=rate_limited,json=rateLimited,proto3" json:"rate_limited,omitempty"`
	DefaultExclusiveJoinTask       []string                                  `protobuf:"bytes,21,rep,name=default_exclusive_join_task,json=defaultExclusiveJoinTask,proto3" json:"default_exclusive_join_task,omitempty"`
	AsyncComplete                  bool                                      `protobuf:"varint,23,opt,name=async_complete,json=asyncComplete,proto3" json:"async_complete,omitempty"`
	LoopCondition                  string                                    `protobuf:"bytes,24,opt,name=loop_condition,json=loopCondition,proto3" json:"loop_condition,omitempty"`
	LoopOver                       []*WorkflowTask                           `protobuf:"bytes,25,rep,name=loop_over,json=loopOver,proto3" json:"loop_over,omitempty"`
	XXX_NoUnkeyedLiteral           struct{}                                  `json:"-"`
	XXX_unrecognized               []byte                                    `json:"-"`
	XXX_sizecache                  int32                                     `json:"-"`
}

func (m *WorkflowTask) Reset()         { *m = WorkflowTask{} }
func (m *WorkflowTask) String() string { return proto.CompactTextString(m) }
func (*WorkflowTask) ProtoMessage()    {}
func (*WorkflowTask) Descriptor() ([]byte, []int) {
	return fileDescriptor_workflowtask_643ff3d9d9c910ca, []int{0}
}
func (m *WorkflowTask) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkflowTask.Unmarshal(m, b)
}
func (m *WorkflowTask) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkflowTask.Marshal(b, m, deterministic)
}
func (dst *WorkflowTask) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkflowTask.Merge(dst, src)
}
func (m *WorkflowTask) XXX_Size() int {
	return xxx_messageInfo_WorkflowTask.Size(m)
}
func (m *WorkflowTask) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkflowTask.DiscardUnknown(m)
}

var xxx_messageInfo_WorkflowTask proto.InternalMessageInfo

func (m *WorkflowTask) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *WorkflowTask) GetTaskReferenceName() string {
	if m != nil {
		return m.TaskReferenceName
	}
	return ""
}

func (m *WorkflowTask) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *WorkflowTask) GetInputParameters() map[string]*_struct.Value {
	if m != nil {
		return m.InputParameters
	}
	return nil
}

func (m *WorkflowTask) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *WorkflowTask) GetDynamicTaskNameParam() string {
	if m != nil {
		return m.DynamicTaskNameParam
	}
	return ""
}

func (m *WorkflowTask) GetCaseValueParam() string {
	if m != nil {
		return m.CaseValueParam
	}
	return ""
}

func (m *WorkflowTask) GetCaseExpression() string {
	if m != nil {
		return m.CaseExpression
	}
	return ""
}

func (m *WorkflowTask) GetScriptExpression() string {
	if m != nil {
		return m.ScriptExpression
	}
	return ""
}

func (m *WorkflowTask) GetDecisionCases() map[string]*WorkflowTask_WorkflowTaskList {
	if m != nil {
		return m.DecisionCases
	}
	return nil
}

func (m *WorkflowTask) GetDynamicForkTasksParam() string {
	if m != nil {
		return m.DynamicForkTasksParam
	}
	return ""
}

func (m *WorkflowTask) GetDynamicForkTasksInputParamName() string {
	if m != nil {
		return m.DynamicForkTasksInputParamName
	}
	return ""
}

func (m *WorkflowTask) GetDefaultCase() []*WorkflowTask {
	if m != nil {
		return m.DefaultCase
	}
	return nil
}

func (m *WorkflowTask) GetForkTasks() []*WorkflowTask_WorkflowTaskList {
	if m != nil {
		return m.ForkTasks
	}
	return nil
}

func (m *WorkflowTask) GetStartDelay() int32 {
	if m != nil {
		return m.StartDelay
	}
	return 0
}

func (m *WorkflowTask) GetSubWorkflowParam() *SubWorkflowParams {
	if m != nil {
		return m.SubWorkflowParam
	}
	return nil
}

func (m *WorkflowTask) GetJoinOn() []string {
	if m != nil {
		return m.JoinOn
	}
	return nil
}

func (m *WorkflowTask) GetSink() string {
	if m != nil {
		return m.Sink
	}
	return ""
}

func (m *WorkflowTask) GetOptional() bool {
	if m != nil {
		return m.Optional
	}
	return false
}

func (m *WorkflowTask) GetTaskDefinition() *TaskDef {
	if m != nil {
		return m.TaskDefinition
	}
	return nil
}

func (m *WorkflowTask) GetRateLimited() bool {
	if m != nil {
		return m.RateLimited
	}
	return false
}

func (m *WorkflowTask) GetDefaultExclusiveJoinTask() []string {
	if m != nil {
		return m.DefaultExclusiveJoinTask
	}
	return nil
}

func (m *WorkflowTask) GetAsyncComplete() bool {
	if m != nil {
		return m.AsyncComplete
	}
	return false
}

func (m *WorkflowTask) GetLoopCondition() string {
	if m != nil {
		return m.LoopCondition
	}
	return ""
}

func (m *WorkflowTask) GetLoopOver() []*WorkflowTask {
	if m != nil {
		return m.LoopOver
	}
	return nil
}

type WorkflowTask_WorkflowTaskList struct {
	Tasks                []*WorkflowTask `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *WorkflowTask_WorkflowTaskList) Reset()         { *m = WorkflowTask_WorkflowTaskList{} }
func (m *WorkflowTask_WorkflowTaskList) String() string { return proto.CompactTextString(m) }
func (*WorkflowTask_WorkflowTaskList) ProtoMessage()    {}
func (*WorkflowTask_WorkflowTaskList) Descriptor() ([]byte, []int) {
	return fileDescriptor_workflowtask_643ff3d9d9c910ca, []int{0, 0}
}
func (m *WorkflowTask_WorkflowTaskList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkflowTask_WorkflowTaskList.Unmarshal(m, b)
}
func (m *WorkflowTask_WorkflowTaskList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkflowTask_WorkflowTaskList.Marshal(b, m, deterministic)
}
func (dst *WorkflowTask_WorkflowTaskList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkflowTask_WorkflowTaskList.Merge(dst, src)
}
func (m *WorkflowTask_WorkflowTaskList) XXX_Size() int {
	return xxx_messageInfo_WorkflowTask_WorkflowTaskList.Size(m)
}
func (m *WorkflowTask_WorkflowTaskList) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkflowTask_WorkflowTaskList.DiscardUnknown(m)
}

var xxx_messageInfo_WorkflowTask_WorkflowTaskList proto.InternalMessageInfo

func (m *WorkflowTask_WorkflowTaskList) GetTasks() []*WorkflowTask {
	if m != nil {
		return m.Tasks
	}
	return nil
}

func init() {
	proto.RegisterType((*WorkflowTask)(nil), "conductor.proto.WorkflowTask")
	proto.RegisterMapType((map[string]*WorkflowTask_WorkflowTaskList)(nil), "conductor.proto.WorkflowTask.DecisionCasesEntry")
	proto.RegisterMapType((map[string]*_struct.Value)(nil), "conductor.proto.WorkflowTask.InputParametersEntry")
	proto.RegisterType((*WorkflowTask_WorkflowTaskList)(nil), "conductor.proto.WorkflowTask.WorkflowTaskList")
}

func init() {
	proto.RegisterFile("model/workflowtask.proto", fileDescriptor_workflowtask_643ff3d9d9c910ca)
}

var fileDescriptor_workflowtask_643ff3d9d9c910ca = []byte{
	// 818 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0xff, 0x6f, 0x1b, 0x35,
	0x14, 0x57, 0xd6, 0xb5, 0x6b, 0x5e, 0xd2, 0x24, 0x75, 0xbb, 0xd5, 0x64, 0x0c, 0xc2, 0x10, 0x22,
	0x12, 0xe8, 0x82, 0x3a, 0x21, 0xd0, 0xa4, 0x49, 0xb0, 0xb6, 0x20, 0x60, 0xb0, 0xea, 0x40, 0x4c,
	0x9a, 0x84, 0x4e, 0x8e, 0xcf, 0x17, 0x4c, 0xee, 0xec, 0x93, 0xed, 0xeb, 0x9a, 0xff, 0x82, 0x3f,
	0x19, 0xf9, 0xf9, 0xae, 0xb9, 0xa5, 0x55, 0x55, 0x7e, 0xb3, 0x3f, 0xef, 0xf3, 0xbe, 0x7c, 0xde,
	0x3d, 0xbf, 0x03, 0x5a, 0xe8, 0x54, 0xe4, 0xb3, 0x77, 0xda, 0x2c, 0xb3, 0x5c, 0xbf, 0x73, 0xcc,
	0x2e, 0xa3, 0xd2, 0x68, 0xa7, 0xc9, 0x90, 0x6b, 0x95, 0x56, 0xdc, 0x69, 0x13, 0x80, 0xf1, 0x41,
	0xa0, 0x7a, 0x4a, 0x2a, 0xb2, 0x1a, 0x7c, 0x12, 0x40, 0x5b, 0xcd, 0x9b, 0x10, 0x25, 0x33, 0xac,
	0xb0, 0xb5, 0xf9, 0xc3, 0x85, 0xd6, 0x8b, 0x5c, 0xcc, 0xf0, 0x36, 0xaf, 0xb2, 0x99, 0x75, 0xa6,
	0xe2, 0x2e, 0x58, 0x9f, 0xfe, 0xdb, 0x87, 0xfe, 0x9b, 0xda, 0xed, 0x0f, 0x66, 0x97, 0x84, 0xc0,
	0x7d, 0xc5, 0x0a, 0x41, 0x3b, 0x93, 0xce, 0xb4, 0x1b, 0xe3, 0x99, 0x44, 0x70, 0xe0, 0x53, 0x26,
	0x46, 0x64, 0xc2, 0x08, 0xc5, 0x45, 0x82, 0x94, 0x7b, 0x48, 0xd9, 0xf7, 0xa6, 0xb8, 0xb1, 0xfc,
	0xe6, 0xf9, 0x13, 0xe8, 0xa5, 0xc2, 0x72, 0x23, 0x4b, 0x27, 0xb5, 0xa2, 0x5b, 0xc8, 0x6b, 0x43,
	0xe4, 0x2f, 0x18, 0x49, 0x55, 0x56, 0x2e, 0xc1, 0x52, 0x85, 0x13, 0xc6, 0xd2, 0xfb, 0x93, 0xad,
	0x69, 0xef, 0xf8, 0x38, 0xda, 0x10, 0x1d, 0xb5, 0xcb, 0x8b, 0x7e, 0xf2, 0x5e, 0xe7, 0x57, 0x4e,
	0x67, 0xca, 0x99, 0x55, 0x3c, 0x94, 0xef, 0xa3, 0x5e, 0x84, 0x5b, 0x95, 0x82, 0x6e, 0x07, 0x11,
	0xfe, 0x4c, 0xbe, 0x86, 0xa3, 0x74, 0xa5, 0x58, 0x21, 0x79, 0x82, 0x62, 0xbc, 0x84, 0x90, 0x9e,
	0xee, 0x20, 0xed, 0xb0, 0x36, 0xfb, 0x3c, 0x5e, 0x06, 0xc6, 0x23, 0x53, 0x18, 0x71, 0x66, 0x45,
	0x72, 0xc1, 0xf2, 0xaa, 0xe1, 0x3f, 0x40, 0xfe, 0xc0, 0xe3, 0x7f, 0x7a, 0x38, 0x30, 0x3f, 0x87,
	0x21, 0x32, 0xc5, 0x65, 0x69, 0x84, 0xb5, 0x5e, 0xf9, 0xee, 0x9a, 0x78, 0x76, 0x85, 0x92, 0x2f,
	0x60, 0x3f, 0x74, 0xa2, 0x4d, 0x7d, 0x84, 0xd4, 0x51, 0x30, 0xb4, 0xc8, 0x6f, 0x60, 0x90, 0x0a,
	0x2e, 0xfd, 0x39, 0xf1, 0x71, 0x2c, 0xed, 0x62, 0x9f, 0xbe, 0xba, 0xbd, 0x4f, 0xa7, 0xb5, 0xcf,
	0x89, 0x77, 0x09, 0x5d, 0xda, 0x4b, 0xdb, 0x18, 0xf9, 0x06, 0x68, 0xd3, 0x8f, 0x4c, 0x9b, 0x25,
	0x36, 0xc5, 0xd6, 0x02, 0x01, 0x8b, 0x79, 0x58, 0xdb, 0x7f, 0xd0, 0x66, 0xe9, 0x83, 0xda, 0xa0,
	0xf3, 0x17, 0xf8, 0xf4, 0x06, 0xc7, 0xd6, 0xe7, 0x0c, 0xd3, 0xd1, 0xc3, 0x18, 0x1f, 0x6d, 0xc6,
	0x58, 0x7f, 0x40, 0x1c, 0x95, 0xef, 0xa0, 0x9f, 0x8a, 0x8c, 0x55, 0xb9, 0x43, 0x75, 0xb4, 0x8f,
	0xe2, 0x9e, 0xdc, 0x2a, 0xce, 0x8f, 0x12, 0xba, 0x78, 0x21, 0xe4, 0x57, 0x80, 0x75, 0x19, 0x74,
	0x0f, 0xfd, 0xa3, 0xdb, 0x9b, 0xd3, 0xbe, 0xbc, 0x92, 0xd6, 0xc5, 0xdd, 0xac, 0x29, 0x8f, 0x7c,
	0x0c, 0x3d, 0xeb, 0x98, 0x71, 0x49, 0x2a, 0x72, 0xb6, 0xa2, 0x83, 0x49, 0x67, 0xba, 0x1d, 0x03,
	0x42, 0xa7, 0x1e, 0x21, 0xe7, 0x40, 0x6c, 0x35, 0x4f, 0x9a, 0xb7, 0x56, 0x77, 0x6c, 0x38, 0xe9,
	0x4c, 0x7b, 0xc7, 0x4f, 0xaf, 0xe5, 0xfd, 0xbd, 0x9a, 0x37, 0xd9, 0x50, 0xb4, 0x8d, 0x47, 0x76,
	0x03, 0x22, 0x47, 0xf0, 0xe0, 0x1f, 0x2d, 0x55, 0xa2, 0x15, 0x1d, 0x4d, 0xb6, 0xa6, 0xdd, 0x78,
	0xc7, 0x5f, 0x5f, 0x2b, 0x3f, 0xc6, 0x56, 0xaa, 0x25, 0xdd, 0x0f, 0x63, 0xec, 0xcf, 0x64, 0x0c,
	0xbb, 0x1a, 0xdf, 0x10, 0xcb, 0x29, 0x99, 0x74, 0xa6, 0xbb, 0xf1, 0xd5, 0x9d, 0x7c, 0x0f, 0x43,
	0x1c, 0xed, 0x54, 0x64, 0x52, 0x49, 0x7c, 0x7b, 0x07, 0x58, 0x17, 0xbd, 0x56, 0x97, 0x17, 0x7b,
	0x2a, 0xb2, 0x78, 0xe0, 0xc2, 0xa1, 0xe6, 0x93, 0x4f, 0xa0, 0x6f, 0x98, 0x13, 0x49, 0x2e, 0x0b,
	0xe9, 0x44, 0x4a, 0x0f, 0x31, 0x45, 0xcf, 0x63, 0xaf, 0x02, 0x44, 0x5e, 0xc0, 0xe3, 0xe6, 0x93,
	0x89, 0x4b, 0x9e, 0x57, 0x56, 0x5e, 0x88, 0x04, 0x05, 0xf8, 0x58, 0xf4, 0x21, 0x4a, 0xa0, 0x35,
	0xe5, 0xac, 0x61, 0xfc, 0xac, 0xa5, 0xc2, 0x05, 0xf3, 0x19, 0x0c, 0x98, 0x5d, 0x29, 0x9e, 0x70,
	0x5d, 0x94, 0xb9, 0x70, 0x82, 0x1e, 0x61, 0x8e, 0x3d, 0x44, 0x4f, 0x6a, 0xd0, 0xd3, 0x72, 0xad,
	0xcb, 0xc4, 0x17, 0x1e, 0xa4, 0x50, 0xec, 0xc2, 0x9e, 0x47, 0x4f, 0x1a, 0x90, 0x3c, 0x87, 0x2e,
	0xd2, 0xf4, 0x85, 0x30, 0xf4, 0x83, 0xbb, 0x0c, 0xcf, 0xae, 0xe7, 0xbf, 0xbe, 0x10, 0x66, 0xfc,
	0x23, 0x8c, 0x36, 0x27, 0x81, 0x3c, 0x83, 0xed, 0x30, 0x48, 0x9d, 0xbb, 0xc4, 0x0a, 0xdc, 0xf1,
	0x5b, 0x38, 0xbc, 0x69, 0x2f, 0x91, 0x11, 0x6c, 0x2d, 0xc5, 0xaa, 0x5e, 0xa5, 0xfe, 0x48, 0xbe,
	0x84, 0x6d, 0x5c, 0x24, 0xb8, 0x3b, 0x7b, 0xc7, 0x8f, 0xa2, 0xb0, 0x9c, 0xa3, 0x66, 0x39, 0x47,
	0xb8, 0x4f, 0xe2, 0x40, 0x7a, 0x7e, 0xef, 0xdb, 0xce, 0xb8, 0x04, 0x72, 0xfd, 0x2d, 0xdf, 0x10,
	0xf9, 0xf4, 0xfd, 0xc8, 0xff, 0xf7, 0x05, 0xac, 0x33, 0xbe, 0xcc, 0xe1, 0x31, 0xd7, 0x45, 0xa4,
	0x84, 0xcb, 0x72, 0x79, 0xb9, 0x19, 0xe7, 0xe5, 0xa0, 0xed, 0x7b, 0x3e, 0x7f, 0xfb, 0x62, 0x21,
	0xdd, 0xdf, 0xd5, 0x3c, 0xe2, 0xba, 0x98, 0x15, 0x8c, 0x3b, 0xb6, 0x58, 0x30, 0xe3, 0x66, 0x57,
	0x6e, 0x33, 0x9e, 0x4b, 0xa1, 0xdc, 0x6c, 0xa1, 0x17, 0xa6, 0xe4, 0x2d, 0x1c, 0x7f, 0x5b, 0xf3,
	0x1d, 0x8c, 0xfa, 0xec, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x70, 0xe7, 0x58, 0x97, 0x06, 0x07,
	0x00, 0x00,
}
